version: '3.5'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      # App
      - "./src/:/app/src/"
      - "./public/img:/app/public/img"
      - "./public/index.html:/app/public/index.html"
      # Root Config Files
      - "./rollup.config.js:/app/rollup.config.js"
      - "./tailwind.config.js:/app/tailwind.config.js"
      - "./postcss.config.js:/app/postcss.config.js"
      - "./package.json:/app/package.json"
      - "./package-lock.json:/app/package-lock.json"
      - "./tsconfig.json:/app/tsconfig.json"
      # NGINX Conf
      # - "/default.conf:/etc/nginx/conf.d/default.conf"
